{"name": "test_cass001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.Testlogin object at 0x00000185EF109B50>\n\n    def test_cass001(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:3: AssertionError"}, "start": 1638169626555, "stop": 1638169626555, "uuid": "b1081fca-7428-4e38-becf-ba1b4239391b", "historyId": "2edc3356bb968eb39a0b309a198e39b8", "testCaseId": "67cc5e2e5e13d75325d490c238d3dd13", "fullName": "scripts.test_login.Testlogin#test_cass001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "WIN-UF6G7HQ7R7A"}, {"name": "thread", "value": "12868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}